### ISSUE TITLE
Tagging Releases on Github

### ISSUE THREAD

**Issue by frantisekz** [kapouille/mongoquery#18]
Hi,
I am package maintainer of mongoquery in Fedora (python-mongoquery). I see there are new versions of mongoquery on PyPi, but they are not tagged on github.

Will it be possible to tag new versions also here?

Thanks!

**Comment by kapouille** [comment]
Sure, if that can help.

**Comment by kapouille** [comment]
I just tagged the latest version.

**Comment by frantisekz** [comment]
> Sure, if that can help.

Yep, I'll get notifications of new releases.

Thank you very much!

**Comment by frantisekz** [comment]
Hi @kapouille , can you go ahead and tag also the 1.3.6? Thanks a lot (I am working on Fedora package upgrade and pypi archive doesn't contain tests).

Thanks a lot!

**Comment by kapouille** [comment]
You're a demanding customer! There, all tagged for you!
