### ISSUE TITLE
 Importing ABC directly from collections module was removed in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [kapouille/mongoquery#21]
https://bugzilla.redhat.com/show_bug.cgi?id=1792973

https://github.com/kapouille/mongoquery/blob/26290742751ef7c34a7731d5fe9a45c205019001/mongoquery/__init__.py#L7

Thanks for the library!

**Comment by kapouille** [comment]
thank you @ch3pjw for the fix, this is now released in `1.3.6` in `PyPi`

**Comment by ch3pjw** [comment]
You're welcome @kapouille :+1:
