### ISSUE TITLE
$exists doesn't seem to work correctly for nested objects

### ISSUE THREAD

**Issue by opichals** [kapouille/mongoquery#25]
Looks like the current implementation fails for the following:

```
import mongoquery

q = mongoquery.Query({"obj.id": {"$exists": True, "$regex": "no match"}})

assert q.match({"obj": {"id": "some-id"}}) == False
```

with
```
Traceback (most recent call last):
  File "/tmp/mq/mq.py", line 5, in <module>
    assert q.match({"obj": {"id": "some-id"}}) == False
AssertionError
```

**Comment by opichals** [comment]
Studying the code I wonder what is the logic behind the `_exists = _noop` (at [__init__.py#L290](https://github.com/kapouille/mongoquery/blob/master/mongoquery/__init__.py#L290))

**Comment by opichals** [comment]
🤦‍♂️ , I am sorry, I guess the query should have been:

```
mongoquery.Query({"obj.id": {"$and": [{"$exists": True}, {"$regex": "some-id"}]}})
```

In which case it works as expected. But still wonder about the workings around the `_exists = _noop`.

**Comment by kapouille** [comment]
No worries 😉 

It's been a very long time since I wrote this, but if my very hazy memory serves right, the simple fact of getting to run that function means the member has already been found. Hence it only needing to be a `noop`

**Comment by opichals** [comment]
Thank you! :)
